export const dataService = [
    {
        id:1,
        image:"../../../img-service-1.png",
        imgStart: false,
        title:"모두 시그니처만의 효과적인 기능",
        widthTitle:"296px",
        pharagraph1:"템플릿 저장 및 불러오기",
        detailPharagraph1:"자주 사용하는 문서를 저장하고 필요할 때 마다 템플릿을 불러와 빠르게 작업할 수 있습니다.",
        pharagraph2:"폴더 설정 ",
        detailPharagraph2:"별도로 관리가 필요한 문서들은 폴더 설정을 통해보다 체계적으로 관리할 수 있습니다.",
        pharagraph3:"텍스트 및 체크박스 입력 ",
        detailPharagraph3:"텍스트, 체크박스를 설정하여 문서에 텍스트를 자유롭게입력하고 상대방의 동의 여부를 확인할 수 있습니다.",
        pharagraph4:"다양한 파일형식 지원",
        detailPharagraph4:"한글, 오피스 계열(Word, PPT, Excel), PDF부터 JPG, PNG,GIF, BMP와 같은 이미지 파일까지 변환없이 업로드하고사용할 수 있습니다.",

    },
    {
        id:2,
        image:"../../../img-service-2.png",
        imgStart: true,
        title:"계약을 쉽고 빠르게체결하는 방법!",
        widthTitle:"308px",
        pharagraph1:"공인인증서 없는 본인인증",
        detailPharagraph1:"공인인증서와 ActiveX가 필요 없습니다. 이메일 인증,휴대폰 인증, 암호인증 설정으로 간편하게 본인인증 해 보세요.",
        pharagraph2:"카카오톡으로 서명 요청하기 ",
        detailPharagraph2:"카카오톡으로 상대방에게 서명을 요청해보세요. 상대방은 PC, 모바일 언제 어디에서나 계약서에 서명할 수 있습니다.",
        pharagraph3:"계약 체결과 보안 ",
        detailPharagraph3:"누구나 이용하기 쉬운 직관적인 흐름으로 빠르고 신속하게 계약을 체결하고, 이후에도 지속적으로 관리할 수 있습니다. ",
        pharagraph4:"가입 없이 즉시 서명",
        detailPharagraph4:"계약 상대방은 번거로운 회원가입 절차 없이 간편인증 후 즉시 서명할 수 있습니다.",

    },
    {
        id:3,
        image:"../../../img-service-3.png",
        imgStart: false,
        title:"수월하게 계약을완료하세요",
        widthTitle:"263px",
        pharagraph1:"감사추적인증서를 통한 증명 ",
        detailPharagraph1:"계약완료시 원본과 함께 발급되는 ‘감사추적인증서’로 계약당사자의 행위를 쉽게 증명할 수 있습니다.",
        pharagraph2:"혼자 서명하기",
        detailPharagraph2:"동의서, 영수증 같이 본인만 서명하는 문서에도 빠르게서명할 수 있습니다.",
        pharagraph3:"다양한 드라이브 업로드 지원 ",
        detailPharagraph3:"다양한 드라이브 업로드 지원 ",
        pharagraph4:"다양한 드라이브 업로드 지원",
        detailPharagraph4:"내문서함에서 계약 문서별로 내용 확인하기, 계약서 다운로드,공유하기, 삭제하기가 가능합니다.",

    },
]